# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AgenticDialog',
                'doc_host': 'https://abdulahad.github.io',
                'git_url': 'https://github.com/abdulahad/AgenticDialog',
                'lib_path': 'AgenticDialog'},
  'syms': {'AgenticDialog.core': {'AgenticDialog.core.foo': ('core.html#foo', 'AgenticDialog/core.py')}}}
